### ISSUE TITLE
Tools support for LLM 0.26a0

### ISSUE THREAD

**Issue by simonw** [taketwo/llm-ollama#46]
Just a heads up that I hope to have an alpha release out for tool support in the next 24ish hours.

I plan to have this working for OpenAI and Anthropic and Gemini on launch day, it would be great to have it in Ollama as well.

The API is not quite stable yet, but I can have a PR ready at the moment it is.

Here is my WIP: https://github.com/simonw/llm-ollama/commits/215b44d2d2b1d8783b948ae19bf648764f98e8f0/

Tracking issue:
- https://github.com/simonw/llm/issues/898

**Comment by taketwo** [comment]
Thanks for the heads-up. I'm on board for merging/releasing Ollama support, especially if you would have a working PR ready.

**Comment by simonw** [comment]
As far as I can tell there's no easy way to check which Ollama models available locally support tools - few of them do at the moment.

I filed an issue about that here:
- https://github.com/ollama/ollama/issues/10693

In the meantime I set o3 on it and it [suggested something like this](https://chatgpt.com/share/6823a769-78a4-8006-af80-382fe10194d5) which I have not yet tried:
```python
import httpx, json, re

client = httpx.Client(base_url="http://localhost:11434")

local = client.get("/api/tags").json()["models"]      # ↳ [{name:'llama3.1',size:…}, …]
tool_ready = []

for m in local:
    tmpl = client.post("/api/show", json={"name": m["name"],
                                          "format":"json"}).json()["template"]
    if re.search(r'\.\s*Tools\s*}}', tmpl):           # very fast heuristic
        tool_ready.append(m["name"])

print("Local models with tool support:", tool_ready)
```

**Comment by simonw** [comment]
Oh interesting: There's already similar code on here: https://github.com/taketwo/llm-ollama/blob/4c91d4544ae6267ffa5670ed07c928797c7ee11e/llm_ollama/__init__.py#L387-L410

**Comment by simonw** [comment]
PR is up:
- https://github.com/taketwo/llm-ollama/pull/48

**Comment by simonw** [comment]
Wow, that code that o3 [wrote earlier](https://github.com/taketwo/llm-ollama/issues/46#issuecomment-2877824852) appears to work!
```pycon
>>> import httpx, json, re
... 
... client = httpx.Client(base_url="http://localhost:11434")
... 
... local = client.get("/api/tags").json()["models"]      # ↳ [{name:'llama3.1',size:…}, …]
... tool_ready = []
... 
... for m in local:
...     tmpl = client.post("/api/show", json={"name": m["name"],
...                                           "format":"json"}).json()["template"]
...     if re.search(r'\.\s*Tools\s*}}', tmpl):           # very fast heuristic
...         tool_ready.append(m["name"])
... 
... print("Local models with tool support:", tool_ready)
... 
Local models with tool support: ['llama3.2:latest', 'qwen3:4b', 'mistral-small3.1:latest', 'qwen3:32b', 'phi4-mini:latest', 'mistral-small:24b', 'llama3.2:3b']
>>> 
```

**Comment by simonw** [comment]
With that change in place:
```bash
llm models -q ollama --options
```
returns:
```yaml
Ollama: llama3.2:3b (aliases: llama3.2:latest, llama3.2)
  Options:
    mirostat: int
      Enable Mirostat sampling for controlling perplexity.
    mirostat_eta: float
      Influences how quickly the algorithm responds to feedback from the
      generated text.
    mirostat_tau: float
      Controls the balance between coherence and diversity of the output.
    num_ctx: int
      The size of the context window used to generate the next token.
    temperature: float
      The temperature of the model. Increasing the temperature will make the
      model answer more creatively.
    seed: int
      Sets the random number seed to use for generation. Setting this to a
      specific number will make the model generate the same text for the
      same prompt.
    stop: array
      Sets the stop sequences to use. When this pattern is encountered the
      LLM will stop generating text and return.
    tfs_z: float
      Tail free sampling is used to reduce the impact of less probable
      tokens from the output.
    num_predict: int
      Maximum number of tokens to predict when generating text.
    top_k: int
      Reduces the probability of generating nonsense.
    top_p: float
      Works together with top-k. A higher value (e.g., 0.95) will lead to
      more diverse text, while a lower value (e.g., 0.5) will generate more
      focused and conservative text.
    json_object: boolean
      Output a valid JSON object {...}. Prompt must mention JSON.
  Attachment types:
    image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - tools
  - async
Ollama: qwen3:4b
  Options:
    mirostat: int
    mirostat_eta: float
    mirostat_tau: float
    num_ctx: int
    temperature: float
    seed: int
    stop: array
    tfs_z: float
    num_predict: int
    top_k: int
    top_p: float
    json_object: boolean
  Attachment types:
    image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - tools
  - async
Ollama: mistral-small3.1:latest (aliases: mistral-small3.1)
  Options:
    mirostat: int
    mirostat_eta: float
    mirostat_tau: float
    num_ctx: int
    temperature: float
    seed: int
    stop: array
    tfs_z: float
    num_predict: int
    top_k: int
    top_p: float
    json_object: boolean
  Attachment types:
    image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - tools
  - async
Ollama: phi4-reasoning:latest (aliases: phi4-reasoning)
  Options:
    mirostat: int
    mirostat_eta: float
    mirostat_tau: float
    num_ctx: int
    temperature: float
    seed: int
    stop: array
    tfs_z: float
    num_predict: int
    top_k: int
    top_p: float
    json_object: boolean
  Attachment types:
    image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - async
Ollama: phi4-mini-reasoning:latest (aliases: phi4-mini-reasoning)
  Options:
    mirostat: int
    mirostat_eta: float
    mirostat_tau: float
    num_ctx: int
    temperature: float
    seed: int
    stop: array
    tfs_z: float
    num_predict: int
    top_k: int
    top_p: float
    json_object: boolean
  Attachment types:
    image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - async
Ollama: qwen3:32b
  Options:
    mirostat: int
    mirostat_eta: float
    mirostat_tau: float
    num_ctx: int
    temperature: float
    seed: int
    stop: array
    tfs_z: float
    num_predict: int
    top_k: int
    top_p: float
    json_object: boolean
  Attachment types:
    image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - tools
  - async
Ollama: phi4-mini:latest (aliases: phi4-mini)
  Options:
    mirostat: int
    mirostat_eta: float
    mirostat_tau: float
    num_ctx: int
    temperature: float
    seed: int
    stop: array
    tfs_z: float
    num_predict: int
    top_k: int
    top_p: float
    json_object: boolean
  Attachment types:
    image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - tools
  - async
Ollama: hf.co/allenai/OLMo-2-0325-32B-Instruct-GGUF:Q5_0
  Options:
    mirostat: int
    mirostat_eta: float
    mirostat_tau: float
    num_ctx: int
    temperature: float
    seed: int
    stop: array
    tfs_z: float
    num_predict: int
    top_k: int
    top_p: float
    json_object: boolean
  Attachment types:
    image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - async
Ollama: gemma3:27b
  Options:
    mirostat: int
    mirostat_eta: float
    mirostat_tau: float
    num_ctx: int
    temperature: float
    seed: int
    stop: array
    tfs_z: float
    num_predict: int
    top_k: int
    top_p: float
    json_object: boolean
  Attachment types:
    image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - async
Ollama: gemma3:4b
  Options:
    mirostat: int
    mirostat_eta: float
    mirostat_tau: float
    num_ctx: int
    temperature: float
    seed: int
    stop: array
    tfs_z: float
    num_predict: int
    top_k: int
    top_p: float
    json_object: boolean
  Attachment types:
    image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - async
Ollama: mistral-small:24b
  Options:
    mirostat: int
    mirostat_eta: float
    mirostat_tau: float
    num_ctx: int
    temperature: float
    seed: int
    stop: array
    tfs_z: float
    num_predict: int
    top_k: int
    top_p: float
    json_object: boolean
  Attachment types:
    image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - tools
  - async
Ollama: deepseek-r1:1.5b
  Options:
    mirostat: int
    mirostat_eta: float
    mirostat_tau: float
    num_ctx: int
    temperature: float
    seed: int
    stop: array
    tfs_z: float
    num_predict: int
    top_k: int
    top_p: float
    json_object: boolean
  Attachment types:
    image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - async
Ollama: phi4:latest (aliases: phi4)
  Options:
    mirostat: int
    mirostat_eta: float
    mirostat_tau: float
    num_ctx: int
    temperature: float
    seed: int
    stop: array
    tfs_z: float
    num_predict: int
    top_k: int
    top_p: float
    json_object: boolean
  Attachment types:
    image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - async
```
That looks correct to me - the models that uspport tools have `- tools` in their Features list.
